#+STARTUP: indent
#+HUGO_BASE_DIR: ../
#+SEQ_TODO: TODO DRAFT DONE
#+COLUMNS: %TODO %42ITEM %TAGS

* Pages
:PROPERTIES:
:EXPORT_HUGO_SECTION:
:EXPORT_HUGO_TYPE: page
:END:
** DONE About
:PROPERTIES:
:EXPORT_FILE_NAME: about
:EXPORT_DATE: 2017-08-21T19:39:01+05:30
:END:

Thatte Idli Kaal Soup is a food-loving Ultimate Frisbee club from Bangalore. It
currently has three teams as a part of the club:

1. TIKS
2. Dabaki
3. Discturbia

Below is a timeline of some of the major events for the club

{{% events %}}
** Favorites
:PROPERTIES:
:EXPORT_FILE_NAME: favorites
:END:

Here's a YouTube playlist of some of our favorite matches

#+BEGIN_EXPORT html
<iframe width="800" height="600" src="https://www.youtube.com/embed/videoseries?list=PLo98-81j1ocKl5JawUZN2ad1WMXCn79ua" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
#+END_EXPORT

* Posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts
:EXPORT_HUGO_TYPE: post
:END:
** DONE TIKS League — Masala Idli
:PROPERTIES:
:EXPORT_FILE_NAME: masala-idli
:EXPORT_DATE: 2017-08-21T14:39:01+05:30
:END:

*** League Schedule

| Date     | 6:05 -- 6:50 am | 6:55 - 7:40 am   |
|----------+-----------------+------------------|
| Aug 5    | 1 vs. 2         | 3 vs. 4          |
| +Aug 12+ | IISc HAT        | IISc HAT         |
| Aug 19   | 2 vs. 4         | 1 vs. 3          |
| +Aug 26+ | U24 camp        | Ganesh Chaturthi |
| +Sep 2+  | Washed out      | Washed out       |
| +Sep 9+  | Washed out      | Washed out       |
| Sep 16   | 1 vs. 4         | 2 vs. 3          |
| Sep 23   | 1 vs. 3         | 2 vs. 4          |
| +Sep 30+ | Chennai Heat    | Chennai Heat     |

*1*: Hubba Hubba,  *2*: GST, *3*: Discpickable Us 3, *4*: Force Four

The schedule is *tentative* and is subject to change, as the league progresses.
Captains will be notified of any changes.

*** Scores and Points table

| A                 |     |     | B                    |
|-------------------+-----+-----+----------------------|
| *Hubba Hubba*     | *9* | 1   | GST                  |
| Discpickable Us 3 |   6 | *9* | *Force Four*         |
| GST               |   4 | *8* | *Force Four*         |
| Hubba Hubba       |   5 | *9* | *Discpickable Us 3*  |
| Hubba Hubba       |   4 | *7* | *Force Four*         |
| GST               |   8 | 8   | Discpickable Us 3    |
#+TBLFM: $1='(identity remote(full-table, @@#$1))
#+TBLFM: $2 = '(identity remote(full-table, @@#$2))
#+TBLFM: $3 = '(identity remote(full-table, @@#$6))
#+TBLFM: $4 = '(identity remote(full-table, @@#$7))

**** COMMENT Full points table

#+NAME: full-table
| A                 |     | MVP    | MSP    | Best-play             |     | B                    | MVP           | MSP   | Best-play             |
|-------------------+-----+--------+--------+-----------------------+-----+----------------------+---------------+-------+-----------------------|
| *Hubba Hubba*     | *9* | Dose   | Nico   | -                     | 1   | GST                  | Pavan & Nikki | Yogi  | Vinuth (to Yogi)      |
| Discpickable Us 3 |   6 | Sasi   | VK     | Venkata               | *9* | *Force Four*         | Krish         | KK    | Amith (to Punch)      |
| GST               |   4 | Nikki  | Vinuth | Yogi (end-zone catch) | *8* | *Force Four*         | Rajan & Saqqu | Team  | Danish                |
| Hubba Hubba       |   5 | Birdie | Team   | Kasi                  | *9* | *Disccpickable Us 3* | VK & Sheetal  | -     | Anirudh               |
| Hubba Hubba       |   4 | Birdie | Nico   | Saru (catch)          | *7* | *Force Four*         | Kedar         | Punch | Kedar (end-zone grab) |
| GST               |   8 |        |        |                       | 8   | Disccpickable Us 3   |               |       |                       |

*** Moments and memories

{{< instagram BXZzh2HhsvF >}}

{{< instagram BXZS2h2Bu5J hidecaption >}}

{{< instagram BXZTgwrhtSW hidecaption >}}

*** League format and Rules

- Rules :: Games will use the [[https://rules.wfdf.org/][WFDF 2017]] rules for the tournament.
- Target :: The game will be played until one of the team scores 9 points.
- Time cap :: The time cap occurs after 40 minutes of game time, if the target
              has not been reached. At the time cap, play continues till the
              completion of the current point. If no team has reached the target
              (9), one goal is added to the highest score to determine the time
              cap target. Play continues until one of the teams reaches this
              time cap target.
- Half time :: There will be *no* half-time during the games.
- Time outs :: Each team has one time out of 2 minutes per game. The time cap
               does not affect the number of time outs available to teams.
- Captains :: A team must have one designated captain and one designated spirit
              captain per game.
- Accreditation :: Teams are encouraged to get all of their players to take the
                   WFDF standard accreditation, at least by the end of August.
                   Points will be awarded to teams for this.
- Teams & Time :: Both teams are required to have 7 players on the line at the
                  designated start time.
  - Teams are given a grace period of 2 minutes to start the game.
  - At the end of 2 minutes, if a team cannot have 7 players on the line, they
    lose a time-out.
  - After that, for a delay of every two minutes, a team concedes 2 points to
    the other team (assuming they have their 7 players on the line).
  - If both teams do not have 7 players, on the line, one point is cut from the
    target (9 goals), for every two minutes.
  - At the end of 20 minutes, if a team has not fielded 7 players, they must
    forfeit the game. If both teams were offending, they will both record a loss
    in the points table.
  - The /next scheduled game will begin 5 minutes later/. Teams playing the
    second game are expected to line up by *6:30 am* if the first game gets
    forfeited. Please reach the field accordingly.
- Time between pulls :: Teams are encouraged to start the next point as quickly
     as they can. Rush back to the end-zone after each point, and aim to start
     within 75 seconds after a point has started. These rules may be enforced,
     as we progress through the league.
- Gender ratio (men:women) :: The squads/teams have been divided to have a ratio
     of somewhere in between 5:2 and 4:3, based on the number of sign-ups.
     Ideally, we would like a 4:3 or even 3:4 ratio, but based on the turnout on
     a given day, the captains can agree to play 5:2. Teams are also encouraged
     to play 4:3 against a 5:2 line, if the players are happy to do so.
- Points will be awarded to teams in the following categories
  1) TIKS league:
     - Win/Loss
     - Best Spirit
     - Best Play
  2) "Ulti-MATE" - individual event when your team is not playing
     - Hitting the cone (any throw)
     - Longest Huck
     - Longest Pull
     - few more to come ...
  3) "friEND-ZONEd" - team event post both the games
     - Most pushups with High Five in a minute (2 people)
     - Relay between cones (4 people)
     - 40 yard dash carrying a team member (2 people)
     - many more to come ...

*** Teams

#+BEGIN_EXPORT html
<p data-height="1000" data-theme-id="light" data-slug-hash="zdKxaN" data-default-tab="result" data-user="punchagan" data-embed-version="2" data-pen-title="TIKS Leage — Masala Idli Edition" class="codepen">See the Pen <a href="https://codepen.io/punchagan/pen/zdKxaN/">TIKS Leage — Masala Idli Edition</a> by Puneeth Chaganti (<a href="https://codepen.io/punchagan">@punchagan</a>) on <a href="https://codepen.io">CodePen</a>.</p>
<script async src="https://production-assets.codepen.io/assets/embed/ei.js"></script>
#+END_EXPORT

** DONE Game video data on calls in games
CLOSED: [2018-02-21 Wed 11:36]
:PROPERTIES:
:EXPORT_FILE_NAME: rules-video-db
:END:

We are trying to create a database of calls in game videos, to help people learn
the rules better. If you'd like to help with this, please add the URL and the
time stamp of where the call occured in it, to [[https://docs.google.com/spreadsheets/d/1mOa4FA3libM_l0PlbU8Jq2HDeDqHoJkEvKsr225fIsw/edit#gid=0][our DB]].

*** On a Desktop/Laptop browser

If you are watching the video on a latptop, you can use the bookmarklet. [[https://youtu.be/qx3NxdjajHk?t=25][Drag
and drop]] the link below (Capture Call) to your bookmarks bar.

#+BEGIN_EXPORT html
<a style="padding: 10px; border: 1px dashed black;"
   href='javascript: (function() {   var GDOC_URL =     "https://script.google.com/macros/s/AKfycbwSJ8SBv-sWWjsz7uNrx29-7c0GWhk-os0ZsD_bwM_gU_c3TnzQ/exec";   var player = document.querySelector("#movie_player"),     time = player.getCurrentTime(),     url = player.getVideoUrl();    player.pauseVideo();   console.log(url, time);    var form = document.createElement("form");   form.style.setProperty("top", "0px");   form.style.setProperty("position", "absolute");   form.style.setProperty("z-index", "10000");   form.style.setProperty("background", "white");   form.style.setProperty("padding", "5px");   form.style.setProperty("width", "210px");    var call = document.createElement("input");   call.setAttribute("type", "text");   call.setAttribute("name", "call");   call.setAttribute("id", "call");   call.setAttribute("placeholder", "Enter call name");   call.style.setProperty("width", "200px");   form.append(call);    var comment = document.createElement("textarea");   comment.setAttribute("placeholder", "Additional comments if any... ");   comment.style.setProperty("width", "200px");   comment.style.setProperty("height", "300px");   form.append(comment);    var submit = document.createElement("button");   submit.textContent = "Submit";   form.append(submit);   submit.onclick = function(e) {     e.preventDefault();     submit_data(url, time, call.value, comment.value);     form.remove();   };   submit.style.setProperty("background", "lightgreen");    var cancel = document.createElement("button");   cancel.textContent = "X";   cancel.style.setProperty("border", "0px");   cancel.style.setProperty("background", "red");   cancel.style.setProperty("float", "right");   form.append(cancel);   cancel.onclick = function() {     form.remove();   };    document.body.append(form);    var submit_data = function(url, time, call, comment) {     url = encodeURIComponent(url);     time = encodeURIComponent(time);     call = encodeURIComponent(call);     comment = encodeURIComponent(comment);     var data_url = `${GDOC_URL}?url=${url}&time=${time}&call=${call}&comment=${comment}`;     window.open(data_url);   }; })(); '>
  Capture Call
  </a>
#+END_EXPORT

When you wisht to make a note about a call that you are watching on YouTube, you
can click on the bookmarklet (while you are in the video tab), enter some
information, and click submit. The data will get automatically submitted. This
opens a new tab, that you can close and continue watching the video.

*** On other devices

Unfortunately, on other devices, you will have to manually enter this data into
this [[https://docs.google.com/spreadsheets/d/1mOa4FA3libM_l0PlbU8Jq2HDeDqHoJkEvKsr225fIsw/edit#gid=0][Google sheet]].

* COMMENT Local Variables
# Local Variables:
# org-hugo-allow-export-after-save: t
# org-export-with-author: nil
# End:
