import React, { Component } from 'react';
import {
  VerticalTimeline,
  VerticalTimelineElement,
} from 'react-vertical-timeline-component';
import 'react-vertical-timeline-component/style.min.css';
import eventList from '../../content/timeline.json';
// Dynamically import all the images in assets/images directory
// taken from https://stackoverflow.com/a/42118921
function importAll(r) {
  return r.keys().reduce((urlMap, imagePath) => {
    // imagePath reads like ./saturday.2019.jpg, ./mdp.jpg, etc.
    // we want a map that maps 'saturday.2019' to the URL generated by require.context
    console.log(imagePath);
    const imageName = imagePath
      .slice('./'.length)
      .split('.')
      .slice(0, -1)
      .join('.');
    const imageURL = r(imagePath);
    urlMap[imageName] = imageURL;
    return urlMap;
  }, new Map());
}
const images = importAll(
  require.context('../assets/images/', false, /\.(png|jpe?g|svg)$/)
);

export default class Timeline extends Component {
  createTimeline() {
    return eventList.Events.map((data, index) => {
      return (
        <VerticalTimelineElement
          className="vertical-timeline-element--work"
          contentArrowStyle={{ borderRight: '7px solid  rgb(33, 150, 243)' }}
          iconStyle={{ background: 'rgb(33, 150, 243)', color: '#fff' }}
          date={data.date}
        >
          <h3 className="vertical-timeline-element-title">{data.title}</h3>
          <h4 className="vertical-timeline-element-subtitle">
            {data.subtitle}
          </h4>
          <br />
          <img className="img-fluid" src={images[data.image]} alt="" />
          <p>{data.description}</p>
        </VerticalTimelineElement>
      );
    });
  }

  render() {
    return (
      <div style={{ background: '#D3D3D3' }}>
        <VerticalTimeline>{this.createTimeline()}</VerticalTimeline>
      </div>
    );
  }
}
